---
exclude:
  - "**/node_modules/**/*"
linters:
  ErbSafety:
    enabled: true
  SelfClosingTag:
    enabled: false
  AllowedScriptType:
    enabled: true
    allowed_types:
      - "text/javascript"
      - "module"
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Rails/OutputSafety:
        Enabled: false
