# .rubocop.yml
inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

# this means we add our excludes to the default ones
inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - "db/migrate/2019*" # don't backport migrations
