version: "3.4"

services:
  db:
    ports:
      - "3306:3306"
  rr_db:
    ports:
      - "3307:3306"
  wifi_user_db:
    ports:
      - "3308:3306"
  app:
    platform: linux/arm64/v8
    build:
      dockerfile: .devcontainer/Dockerfile
      args:
        RUN_PRECOMPILATION: "false"

    # command: bash -c "rails restart && yarn && yarn cache clean && rails server -b 0.0.0.0"
    command: bash -c "rails restart && yarn && yarn cache clean && tail -F /dev/null"
    # bundle exec rdbg -n --open=vscode -c -- bin/rails s -b 0.0.0.0
    # command: bash -c "yarn && yarn cache clean && ./bin/rails db:create db:schema:load db:seed && bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/usr/src/app:cached
    ports:
      - "8080:3000"
    stdin_open: true
    tty: true
