mysql: &mysql
  adapter: mysql2
  encoding: utf8
  host: <%= ENV.fetch('DB_HOST') %>
  port: 3306
  username: <%= ENV.fetch('DB_USER') %>
  password: <%= ENV.fetch('DB_PASS') %>

test:
  !!merge <<: *mysql
  database: govwifi_admin_test

development:
  !!merge <<: *mysql
  database: <%= ENV.fetch('DB_NAME') %>

production:
  !!merge <<: *mysql
  database: <%= ENV.fetch('DB_NAME') %>

read_replica:
  adapter: mysql2
  encoding: utf8
  host: <%= ENV.fetch('RR_DB_HOST') %>
  port: 3306
  username: <%= ENV.fetch('RR_DB_USER') %>
  password: <%= ENV.fetch('RR_DB_PASS') %>
  database: <%= ENV.fetch('RR_DB_NAME') %>

wifi_user:
  adapter: mysql2
  encoding: utf8
  host: <%= ENV.fetch('USER_DB_HOST') %>
  port: 3306
  username: <%= ENV.fetch('USER_DB_USER') %>
  password: <%= ENV.fetch('USER_DB_PASS') %>
  database: <%= ENV.fetch('USER_DB_NAME') %>
