staging:
  support_email: 'dev@localhost.com'
  otp_email:
    template_id: '776fff48-3e94-4417-83b0-bff027c16247'
  confirmation_email:
    template_id: '1af17502-9797-4e61-904e-999f6cf259a5'
  reset_password_email:
    template_id: '1672af2e-2acb-463a-95ee-2adad2aaceee'
  invite_email:
    template_id: 'e3b5ca96-9164-462f-a0b0-65d2103c1ab8'
  help_email:
    template_id: '152cf3ff-e0e2-4f41-9ba0-28091db3f37f'
  unlock_account:
    template_id: '41f8744a-ebe0-417e-98c7-09002ff17a95'
  cross_organisation_invitation:
    template_id: 'd360ba95-1e7d-41e4-920c-1255b65f6f65'
  first_ip_survey:
    template_id: 'da84efee-97db-4925-87c4-8981fa1fa3ca'

development:
  support_email: 'dev@localhost.com'
  otp_email:
    template_id: '776fff48-3e94-4417-83b0-bff027c16247'
  confirmation_email:
    template_id: '1af17502-9797-4e61-904e-999f6cf259a5'
  reset_password_email:
    template_id: '1672af2e-2acb-463a-95ee-2adad2aaceee'
  invite_email:
    template_id: 'e3b5ca96-9164-462f-a0b0-65d2103c1ab8'
  help_email:
    template_id: '152cf3ff-e0e2-4f41-9ba0-28091db3f37f'
  unlock_account:
    template_id: '41f8744a-ebe0-417e-98c7-09002ff17a95'
  cross_organisation_invitation:
    template_id: 'd360ba95-1e7d-41e4-920c-1255b65f6f65'
  first_ip_survey:
    template_id: 'da84efee-97db-4925-87c4-8981fa1fa3ca'

test:
  support_email: 'test@localhost'
  otp_email:
    template_id: '776fff48-3e94-4417-83b0-bff027c16247'
  confirmation_email:
    template_id: 'confirm'
  reset_password_email:
    template_id: 'reset'
  invite_email:
    template_id: 'invite'
  help_email:
    template_id: 'help'
  unlock_account:
    template_id: 'unlock'
  cross_organisation_invitation:
    template_id: 'org_invite'
  first_ip_survey:
    template_id: 'first_ip_survey_id'

production:
  support_email: 'govwifi-support@digital.cabinet-office.gov.uk'
  otp_email:
    template_id: '320f23ab-6ed4-42f8-9eb3-c3b5b25f1108'
  confirmation_email:
    template_id: '5f42e490-ce5e-44e7-9104-805136961116'
  reset_password_email:
    template_id: '63f566f6-8ae8-4356-9baa-cb4c3c0a6671'
  invite_email:
    template_id: '21b73fa7-8149-4778-8cba-46287bbfecc5'
  help_email:
    template_id: '5afffbbc-dbbf-4f50-b29d-8d058eb51734'
  unlock_account:
    template_id: '39465eec-632a-4475-82ac-4bd8a45386ea'
  cross_organisation_invitation:
    template_id: '103d1302-f068-4352-af0b-1280b068db01'
  first_ip_survey:
    template_id: 'd9715290-668c-48cc-bbf9-45290df3f414'
