name: admin lint and test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-and-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run lint
        run: make lint
      - name: Run tests
        run: make prebuilt-test
